### ISSUE TITLE
Παρατηρήσεις στο παραδοτέο Α

### ISSUE THREAD

**Issue by bzafiris** [billk97/weather-api#2]
Υπάρχουν οι εξής παρατηρήσεις/προτάσεις σχετικά με το παραδοτέο Α:
- χρειάζεται πιο αναλυτική περιγραφή του ρόλου κάθε microservice, πχ. η Forecast Service συγκεντρώνει στοιχεία πρόγνωσης από την Forecast Provider Service και κάνει προγνώσεις συνδυαστικές ή αναλυτικές προγνώσεις λαμβάνοντας υπόψιν αξιολογήσεις χρηστών.
- επίσης, κάθε προσφερόμενη υπηρεσία από τις μικρο-υπηρεσίες χρειάζεται περιγραφή. Για παράδειγμα τι χρησιμεύουν οι location services που προσφέρονται από την Forecast Service; Τα locations για τα οποία ενδιαφέρεται ο κάθε χρήστης αποτελούν μέρος του profile του και λογικά λαμβάνονται κατά την σύνδεση και έναρξη χρήσης της υπηρεσίας.
- ο ρόλος της ForecastProvider microservice θεωρώ ότι είναι η διαρκής λήψη στοιχείων πρόγνωσης από τους διάφορους providers και για όλα τα υποστηριζόμενα locations άσχετα αν έχουν ζητηθεί από τους χρήστες. Άρα διατηρεί αναλυτικά και ιστορικά στοιχεία πρόγνωσης. Επίσης, διατηρεί λίστα με τους υποστηριζόμενους providers και στοιχεία για την σύνδεση με αυτούς.
- Η αλληλεπίδραση μεταξύ των υπηρεσιών χρειάζεται επίσης κάποιο σύντομο σχολιασμό. Για παράδειγμα, η ForecastService θα κάνει subscribe στην ForecastProvider και θα παράγει προγνώσεις μόνο για τις τοποθεσίες των χρηστών που είναι ήδη ενεργοί. Οι προγνώσεις αυτές θα ενημερώνονται σε τακτά χρονικά διαστήματα, πχ. ανά ώρα. Παλιότερα δεδομένα θα διαγράφονται μετά από κάθε update.

**Comment by billk97** [comment]
@bzafiris can we close the issue?

**Comment by bzafiris** [comment]
Η forecast provider service πως θα λαμβάνει τα δεδομενα από τους διάφορους providers;
Επίσης, χρειάζεται API για να λαμβάνει από αυτή δεδομένα προβλέψεων η υπηρεσία forecast service.
Δείτε τα σχόλια παραπάνω.

**Comment by billk97** [comment]
Η ιδέα είναι ότι τα δεδομένα για τις προγνώσεις του καιρού θα τα έχει και θα τα διαχειρίζεται η forecast service. Θα ενημερώνεται από εξωτερικές υπηρεσίες μέσω ενός `POST` request στο `/forecasts`. Ο ρόλος της forecast provider είναι να διαχειρίζεται/αποθηκεύει τις τρίτες υπηρεσίες που θα μας παρέχουν μετεωρολογικές προβλέψεις. Αν θέλουμε να προσθέσουμε έχτρα λογική στην service provider και να είναι αυτή υπεύθυνη στην για να αποθηκεύει ή να καταχωρεί  μετεωρολογικές προβλέψεις τότε όντος απαιτείται μία αλλαγή στον τρόπο που έχουμε σχεδιάσει το παρών σύστημα μας.

**Comment by bzafiris** [comment]
Στην τρέχουσα έκδοσή του o Forecast Provider δεν κάνει και πολλά, απλώς διατηρεί μια λίστα με τους providers. Νομίζω είναι πιο πρακτικό να συγκεντρώνει τα raw δεδομένα προβλέψεων, ενώ η forecast service να κρατάει μόνο όσο ζητούνται από τους πελάτες και μάλιστα τα πιο πρόσφατα από αυτά. Νομίζω θα γίνει πιο ενδιαφέρουσα η υλοποίηση και πιο πρακτική.

**Comment by billk97** [comment]
Ωραία θα προχωρήσουμε στις απαραίτητες αλλαγές τότε.
